# Site settings
title: George Carter
email: hawkeseven@gmail.com
description: > # keep this and put description below
  Hobbyist Developer
url: "https://HawkeSevenstark.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/georgemcarter/"
github_username: HawkeSevenstark
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
